version: '3.8'

services:
  reverse-proxy:
    image: traefik:latest
    container_name: reverse-proxy
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - php-fpm
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ${PATH_TO_CODEBASE}:/var/www/html
    labels:
      - "traefik.http.routers.nginx.rule=Host(`${BASE_URL}`)"

  php-fpm:
    container_name: php-fpm
    hostname: php-fpm
    env_file:
      - .env
      - ./php-fpm/.xdebug.env
    build:
      args:
        user: ${DEV_USER}
        uid: ${DEV_UID}
      context: ./php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./php-fpm/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php-fpm/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ${PATH_TO_CODEBASE}:/var/www/html
